export const REDACTED_EMAIL = "[REDACTED_EMAIL]";
export const REDACTED_PHONE = "[REDACTED_PHONE]";
export const REDACTED_SECRET = "[REDACTED_SECRET]";
export const REDACTED_JWT = "[REDACTED_JWT]";
export const REDACTED_LONG_STRING = "[REDACTED_LONG_STRING]";
export const REDACTED_FORBIDDEN_FIELD = "[FORBIDDEN_FIELD_REMOVED]";
export const REDACTED_CIRCULAR_REFERENCE = "[REDACTED_CIRCULAR_REFERENCE]";

export const MAX_SAFE_STRING_LENGTH = 512;
